SAMYSkillConfig:
   SkillName: "PickSkill"
   Language: "C++"
   EntryFile: "Pick.cpp"
   EntryFunction: "pickSkill"
   Parameters: 
      - Name: "pickPose"
        DataType: UA_CRCL_PoseDataType
      - Name: "offset"
        DataType: UA_CRCL_FractionDataType
