SAMYSkillConfig:
   SkillName: "GetPoseSkill"
   Language: "C++"
   EntryFile: "GetPoseSkill.cpp"
   EntryFunction: "getPoseSkill"
   Parameters:
      - Name: "dummy"
        DataType: UA_CRCL_FractionDataType
