version: "3.3"
services:
  core:
    image: core
    command: /usr/src/samy/configFiles/start.sh
    ports:
      - 4840:4840 
    volumes:
      - ./configFiles:/usr/src/samy/configFiles
  doosan: 
    command: /bin/bash -c './start.sh 192.168.114.12 12345 h2017 real'
    image: doosan:latest
    network_mode: "host"
    #ports:
    #  - 12345:12345
    tty: true
    volumes: 
      - ./configFiles:/usr/src/samy/configFiles
  controller:
    image: bpmn-controller
    command: python3 Tests/startBPMNController.py core fjm.diagram BPMNbasedController_Configuration_File.yaml
    tty: true
    volumes:
      - ./configFiles:/usr/src/samy/configFiles

