SAMYCoreConfig:
   AppURI: "AppURItest"
   AppName: "AppNameTest"
   Server:
      Port: 4840
      Encryption: false
      Anonymous: true
      CertificatesPath: ""
   Logging:
      Level:
         App: "info"
         OPCUA: "error"
      Path: "logs"
   ConfigFiles:
      SkillsFile: "/usr/src/samy/configFiles/Skills/"
      RobotsFile: "/usr/src/samy/configFiles/RobotsConfiguration.yaml"
      InformationSourcesFile: "/usr/src/samy/configFiles/InformationSources.yaml"
      DataBaseFile: "/usr/src/samy/configFiles/DataBaseFile.yaml"
