SAMYSkillConfig:
   SkillName: "PlaceSkill"
   Language: "C++"
   EntryFile: "Place.cpp"
   EntryFunction: "placeSkill"
   Parameters: 
      - Name: "placePose"
        DataType: UA_CRCL_PoseDataType
      - Name: "offset"
        DataType: UA_CRCL_FractionDataType