SAMYSkillConfig:
   SkillName: "SetGripperSkill"
   Language: "C++"
   EntryFile: "SetGripper.cpp"
   EntryFunction: "setGripperSkill"
   Parameters: 
      - Name: "setting"
        DataType: UA_CRCL_FractionDataType