Robots:
  - Robot:
      Name: RobotUR5
      ID: 1234
      Skills:
        - MoveSkill
        - GripperApproach
        - GripperAttach
        - GetPose
      Address: "10.0.0.27" # "192.168.0.101" 
      Workobject:
        - -0.12
        - -0.4
        - 0.15
        - 0.0
        - 0.0
        - -1.57

